# Use pytorch to do deeplearning

## 1. 预备知识

### 1.1数据操作

#### 1.1.1 创建Tensor

In [2]:
import torch

print("pytorch version: {}".format(torch.__version__))

pytorch version: 2.4.0+cu124


构建一个行向量

In [3]:
tensor_a = torch.arange(0,12) 
tensor_a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
print("张量的存储位置：{}".format(tensor_a.device))

张量的存储位置：cpu


shape属性可以获取tensor实例的形状

In [5]:
tensor_a.shape

torch.Size([12])

numel()方法可以获取tensor实例中元素的总数

In [6]:
tensor_a.numel()

12

view()方法可以改变向量形状

In [7]:
X = tensor_a.view(3,4)
X


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

torch.zero()和ones()方法可以生成固定值为0、1的张量矩阵

In [8]:
torch.zeros((2,3,4))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

python的list可以创建指定的张量矩阵

In [10]:
Y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

torch.randn()方法可以创建一个指定形状，每个元素的值都随机采样于均值为0，标准差为1的正态分布的张量矩阵

In [11]:
torch.randn((3,4))

tensor([[-0.7954, -0.3632, -1.2758,  0.6752],
        [-0.5791,  1.3946,  0.1282,  0.9070],
        [ 2.2179, -1.2055,  0.5266, -1.5867]])

#### 1.1.2 运算

加法

In [12]:
X + Y

tensor([[ 2,  2,  6,  6],
        [ 5,  7,  9, 11],
        [12, 12, 12, 12]])

按元素乘法

In [13]:
X * Y

tensor([[ 0,  1,  8,  9],
        [ 4, 10, 18, 28],
        [32, 27, 20, 11]])

按元素除法

In [14]:
X.float() / Y.float()

tensor([[ 0.0000,  1.0000,  0.5000,  1.0000],
        [ 4.0000,  2.5000,  2.0000,  1.7500],
        [ 2.0000,  3.0000,  5.0000, 11.0000]])

按元素做指数运算

In [15]:
torch.exp(Y.float())


tensor([[ 7.3891,  2.7183, 54.5981, 20.0855],
        [ 2.7183,  7.3891, 20.0855, 54.5981],
        [54.5981, 20.0855,  7.3891,  2.7183]])

乘法

In [16]:
X @ Y.t()

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

torch.cat()方法可以创建多个Tensor连结

In [17]:
# 0为纵向拼接，1为横向拼接
torch.cat((X,Y),0),torch.cat((X,Y),1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  4,  3,  2,  1]]))

判断两个张量矩阵是否相等

In [18]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对单个张量矩阵求和得到一个值

In [19]:
torch.sum(X)

tensor(66)

.item()方法可以把结果变换为Python中的标量

In [20]:
torch.norm(X.float()).item()

22.494443893432617

#### 1.1.3 广播机制

In [21]:
A = torch.arange(0,3).view(3,1)
B = torch.arange(0,2).view(1,2)

A,B

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [22]:
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

#### 1.1.4 索引

In [23]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [25]:
X[1,2] = 9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [27]:
X[1:2, :] = 12
X

tensor([[ 0,  1,  2,  3],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

#### 1.1.5 运算的内存开销

每个操作都会新开内存来存储运算结果

In [28]:
before = id(Y)
Y = Y + X
id(Y) == before

False

把特定结果放到特定内存，torch.zeros_like()方法可以创建形状一致元素为0的张量矩阵
在张量矩阵参数Z后加上[:],后面加上想要写进Z对应内存里的参数。这是开辟了临时内存存储计算结果。

In [29]:
Z = torch.zeros_like(Y)
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

运算符全名函数中的out函数可以实现不开辟临时内存存储结果

In [30]:
torch.add(X,Y,out=Z)
id(Z) == before

True