# Use pytorch to do deeplearning

## 1. 预备知识

### 1.1数据操作

#### 1.1.1 创建Tensor

In [1]:
import torch

print("pytorch version: {}".format(torch.__version__))

pytorch version: 2.4.0+cu124


##### 构建一个行向量

In [2]:
tensor_a = torch.arange(0,12) 
tensor_a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
print("张量的存储位置：{}".format(tensor_a.device))

张量的存储位置：cpu


##### shape属性可以获取tensor实例的形状

In [4]:
tensor_a.shape

torch.Size([12])

##### numel()方法可以获取tensor实例中元素的总数

In [5]:
tensor_a.numel()

12

##### view()方法可以改变向量形状

In [6]:
X = tensor_a.view(3,4)
X


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

##### torch.zero()和ones()方法可以生成固定值为0、1的张量矩阵

In [7]:
torch.zeros((2,3,4))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##### python的list可以创建指定的张量矩阵

In [9]:
Y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

##### torch.randn()方法可以创建一个指定形状，每个元素的值都随机采样于均值为0，标准差为1的正态分布的张量矩阵

In [10]:
torch.randn((3,4))

tensor([[-0.7923, -0.3151,  0.4885, -0.3036],
        [ 0.0609,  1.0860,  0.3765, -0.9419],
        [-0.4653,  0.2527,  1.2501, -0.2420]])

#### 1.1.2 运算

##### 加法

In [11]:
X + Y

tensor([[ 2,  2,  6,  6],
        [ 5,  7,  9, 11],
        [12, 12, 12, 12]])

##### 按元素乘法

In [12]:
X * Y

tensor([[ 0,  1,  8,  9],
        [ 4, 10, 18, 28],
        [32, 27, 20, 11]])

##### 按元素除法

In [13]:
X.float() / Y.float()

tensor([[ 0.0000,  1.0000,  0.5000,  1.0000],
        [ 4.0000,  2.5000,  2.0000,  1.7500],
        [ 2.0000,  3.0000,  5.0000, 11.0000]])

##### 按元素做指数运算

In [14]:
torch.exp(Y.float())


tensor([[ 7.3891,  2.7183, 54.5981, 20.0855],
        [ 2.7183,  7.3891, 20.0855, 54.5981],
        [54.5981, 20.0855,  7.3891,  2.7183]])

##### 乘法

In [15]:
X @ Y.t()

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

##### torch.cat()方法可以创建多个Tensor连结

In [16]:
# 0为纵向拼接，1为横向拼接
torch.cat((X,Y),0),torch.cat((X,Y),1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  4,  3,  2,  1]]))

##### 判断两个张量矩阵是否相等

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

##### 对单个张量矩阵求和得到一个值

In [18]:
torch.sum(X)

tensor(66)

##### .item()方法可以把结果变换为Python中的标量

In [19]:
torch.norm(X.float()).item()

22.494443893432617

#### 1.1.3 广播机制

In [20]:
A = torch.arange(0,3).view(3,1)
B = torch.arange(0,2).view(1,2)

A,B

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

#### 1.1.4 索引

In [22]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])