# Use pytorch to do deeplearning

## 1. 预备知识

### 1.1数据操作

#### 1.1.1 创建Tensor

In [1]:
import torch

print("pytorch version: {}".format(torch.__version__))

pytorch version: 2.4.0+cu124


##### 构建一个行向量

In [3]:
tensor_a = torch.arange(0,12) 
tensor_a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
print("张量的存储位置：{}".format(tensor_a.device))

张量的存储位置：cpu


##### shape属性可以获取tensor实例的形状

In [5]:
tensor_a.shape

torch.Size([12])

##### numel()方法可以获取tensor实例中元素的总数

In [6]:
tensor_a.numel()

12

##### view()方法可以改变向量形状

In [8]:
X = tensor_a.view(3,4)
X


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

##### torch.zero()和ones()方法可以生成固定值为0、1的张量矩阵

In [12]:
torch.zeros((2,3,4))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##### python的list可以创建指定的张量矩阵

In [14]:
Y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

##### torch.randn()方法可以创建一个指定形状，每个元素的值都随机采样于均值为0，标准差为1的正态分布的张量矩阵

In [15]:
torch.randn((3,4))

tensor([[-0.3628,  0.6734, -0.9040,  1.1738],
        [-0.7264,  0.7438,  0.3748,  0.6717],
        [-1.3712, -0.2071, -0.1770,  0.1629]])

#### 1.1.2 运算

##### 加法

In [16]:
X + Y

tensor([[ 2,  2,  6,  6],
        [ 5,  7,  9, 11],
        [12, 12, 12, 12]])

##### 按元素乘法

In [17]:
X * Y

tensor([[ 0,  1,  8,  9],
        [ 4, 10, 18, 28],
        [32, 27, 20, 11]])

##### 按元素除法

In [18]:
X.float() / Y.float()

tensor([[ 0.0000,  1.0000,  0.5000,  1.0000],
        [ 4.0000,  2.5000,  2.0000,  1.7500],
        [ 2.0000,  3.0000,  5.0000, 11.0000]])

##### 按元素做指数运算

In [19]:
torch.exp(Y.float())


tensor([[ 7.3891,  2.7183, 54.5981, 20.0855],
        [ 2.7183,  7.3891, 20.0855, 54.5981],
        [54.5981, 20.0855,  7.3891,  2.7183]])

##### 乘法

In [20]:
X @ Y.t()

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

##### 